### ISSUE TITLE
Link to governance documents

### ISSUE THREAD

**Issue by atkissoncj** [Punderthings/fossfoundation#10]
This is this source of governance documents that contains many of the governance documents for many Foundations. We can either encourage people to put in the link in the schema or somehow automatically connect them. https://www.zotero.org/groups/2310183/foss_governance/library

**Comment by ShaneCurcuru** [comment]
Do you have a specific suggestion?  I don't want to duplicate information in this website that's already on well-maintained sites elsewhere.

For example, what's the minimum number of data pointer fields from this site towards the governance site that would enable researchers to get value out of it?  Would researchers want this automatable (i.e. very specific schema, so that each link has a quantifiable value at the end somehow), or is something like "Here's the top-level corporate governance document" and "per-project level tech governance doc" links that are human readable sufficient?
