### ISSUE TITLE
Getting tax information automatically

### ISSUE THREAD

**Issue by atkissoncj** [Punderthings/fossfoundation#9]
ProPublica has a tool that tries to scrape info from scanned IRS 990 forms (what nonprofits have to submit each year). That ProPublica Nonprofit Explorer has an API. We could automatically get the tax information from ProPublica if a unique identifier is provided. See https://projects.propublica.org/nonprofits/api

**Comment by ShaneCurcuru** [comment]
Yes - code-wise this should be simple, once we define a mapping of what data we want to capture.

Practically, using this API is likely to be 2-3 years behind the times, at a minimum, due to extensions and the many delays in the IRS system.  This also only captures data back to about 2012 when the extracted data format was setup.

In any case, yes, a simple:
`curl https://projects.propublica.org/nonprofits/download-filing?path=2002_08_EO%2F47-0825376_990_200204.pdf`

Does get a JSON structure where you can iterate easily through `"filings_with_data": [...]`, and even for `filings_without_data` they include a `pdf_url` value for use. Thanks for the reminder!

**Comment by ShaneCurcuru** [comment]
On second thought: ProPublica has both licensing and is only a limited set of actual data from 990 forms.  The IRS XML dump forms have much more data, although would require a little more coding work to extract into our own format (for easy use within research).
What fields are most valuable for researchers?  Do we (on the FOSS side) care about things like size of governing body, public support percentages, and what's reported as hours worked & compensation for directors/officers?
